dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable
cache:
  directories:
    - ./node_modules

jobs:
  include:
    - stage: test
      script: timeout=6000 npm run test -- --watch=false --no-progress
    - stage: build
      script: npm run lib:build

after_success:
  - echo 'SUCCESS'

after_failure:
  - echo 'FAIL'
