dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable
cache:
  directories:
    - ./node_modules

jobs:
  include:
    # - stage: install
    #   script: npm install
    - stage: test
    script: karma start garicons/karma.conf.js --single-run
      script: npm run test --no-watch --no-progress --single-run --browsers=ChromeHeadlessNoSandbox
    # - stage: build
    #   script: npm run lib:build

after_success:
  - echo 'SUCCESS'

after_failure:
  - echo 'FAIL'
