dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable
cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run test --no-watch --no-progress --single-run --browsers=ChromeHeadlessNoSandbox

after_success:
  - echo 'SUCCESS'

after_failure:
  - echo 'FAIL'
